CREATE TYPE public.account_type AS ENUM ('Client', 'Admin');

ALTER TYPE public.account_type OWNER TO oldcarstoredb;

-- Table structure for table `inventory`
CREATE TABLE IF NOT EXISTS public.inventory(
   inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   inv_model character varying NOT NULL,
   inv_year character(4) NOT NULL,
   inv_description text NOT NULL,
   inv_image character varying NOT NULL,
   inv_price numeric(9, 0) NOT NULL,
   inv_color character varying NOT NULL,
   CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)  
);

-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);


-- Data for table `inventory`